// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLoCYv5iSOwA9DN-4SwgdpBgiwfdu8jn0',
    appId: '1:600639870533:web:e3ce87c65e0cefdd77b52c',
    messagingSenderId: '600639870533',
    projectId: 'urban-explorer-615d5',
    authDomain: 'urban-explorer-615d5.firebaseapp.com',
    storageBucket: 'urban-explorer-615d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFjPU7ANmJSL8PXIhvxgE1q-eLup-tVnI',
    appId: '1:600639870533:android:eb9fc422004630d177b52c',
    messagingSenderId: '600639870533',
    projectId: 'urban-explorer-615d5',
    storageBucket: 'urban-explorer-615d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXMW6N-wDafLxmMpogNFgC1_iORG_SOA',
    appId: '1:600639870533:ios:7e3219ef8fbb99c877b52c',
    messagingSenderId: '600639870533',
    projectId: 'urban-explorer-615d5',
    storageBucket: 'urban-explorer-615d5.firebasestorage.app',
    iosBundleId: 'hr.algebra.urbanExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoXMW6N-wDafLxmMpogNFgC1_iORG_SOA',
    appId: '1:600639870533:ios:7e3219ef8fbb99c877b52c',
    messagingSenderId: '600639870533',
    projectId: 'urban-explorer-615d5',
    storageBucket: 'urban-explorer-615d5.firebasestorage.app',
    iosBundleId: 'hr.algebra.urbanExplorer',
  );
}
